/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.avb;

import com.pgssoft.httpclient.HttpClientMock;
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.junit.jupiter.api.Assertions.assertTrue;

/*
The test demonstrates an approach to testing app with http client.
Only one test because next the same, but long term coding require.
 */

class AppTest {

    HttpClientMock httpClientMock = new HttpClientMock();
    public static final String USER_AGENT_NAME = "Java 11 HttpClient Agent";

    @Test
    void getCameraListTest() throws Exception {
        App app = new App();
        httpClientMock.onGet("http://localhost:9191")
                .withHeader("User-Agent", USER_AGENT_NAME)
                .doReturnJSON("[\n" +
                        "    {\n" +
                        "        \"id\": 1,\n" +
                        "        \"sourceDataUrl\": \"http://www.mocky.io/v2/5c51b230340000094f129f5d\",\n" +
                        "        \"tokenDataUrl\": \"http://www.mocky.io/v2/5c51b5b6340000554e129f7b?mocky-delay=1s\"\n" +
                        "    }\n" +
                        "]");
        var list = app.getCameraList("http://localhost:9191", httpClientMock);
        assertThat(list.get(0), equalTo(new Camera(1L, "http://www.mocky.io/v2/5c51b230340000094f129f5d", "http://www.mocky.io/v2/5c51b5b6340000554e129f7b?mocky-delay=1s")));
        httpClientMock.verify().get("http://localhost:9191");
    }
}
